from fastapi import FastAPI, UploadFile, Form, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd
import ollama
import os
import tempfile
import re
import warnings
import base64
import io

# Ignore harmless excel style warnings
warnings.simplefilter("ignore", UserWarning)

app = FastAPI(title="MISsion Backend API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def read_root():
    return {"message": "Welcome to MISsion Backend API! Server is running smoothly with Local AI."}

@app.post("/query-data/")
async def query_data(
    file: UploadFile = File(...),
    prompt: str = Form(...)
):
    if not file.filename.endswith(('.xlsx', '.xls', '.csv')):
        raise HTTPException(status_code=400, detail="Only Excel or CSV files are supported.")

    try:
        suffix = ".csv" if file.filename.endswith(".csv") else ".xlsx"
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as temp:
            content = await file.read()
            temp.write(content)
            temp_path = temp.name

        if suffix == ".csv":
            df = pd.read_csv(temp_path)
        else:
            df = pd.read_excel(temp_path)

        os.remove(temp_path)

        # Extract schema after cleaning dataframe
        df.columns = df.columns.astype(str).str.strip().str.lower()
        
        # Rename notoriously long columns to what the HOD naturally types
        df.rename(columns={
            'cumulative_grade_point_average': 'cgpa',
            'student_name': 'name'
        }, inplace=True)

        for col in df.columns:
            try:
                df[col] = pd.to_numeric(df[col], errors='ignore')
            except Exception:
                pass
                
        # Lowercase all string columns to make equality matching easy
        for col in df.select_dtypes(include=['object']).columns:
            df[col] = df[col].astype(str).str.strip().str.lower()
            
        columns = df.dtypes.to_dict()
        schema_str = ", ".join(df.columns)
        
        system_prompt = f"""You are a pandas expert. You have a DataFrame named `df`.
The ONLY valid columns you can use are: {schema_str}
Note: All text data in the dataframe is in lowercase.

The user will ask a question. Write a SINGLE line of Python pandas code to answer it.
Store the answer in a variable named `result`.

RULES:
- ONLY output the python code. No explanations.
- Make sure parentheses () and brackets [] match correctly.
- CRITICAL: You MUST use the exact column names from the list above. Do not guess or invent column names.
- When filtering by text, ALWAYS use .astype(str).str.contains('text') to prevent integer errors!
- If the user asks to see specific details (like 'name' and 'cgpa'), you MUST select only those columns at the end of your code.
- CRITICAL: Carefully read WHICH column the user wants to filter! If they say "register number containing 24mis", you MUST search the register_number column!

EXAMPLE:
```python
# If user asks: "Show me students with cgpa > 9 in computer science branch"
result = df[(df['cgpa'] > 9) & (df['branch'].astype(str).str.contains('computer science'))][['name', 'cgpa']]
```
"""
        
        ai_response = ollama.generate(
            model='qwen2.5-coder:1.5b',
            system=system_prompt,
            prompt=prompt
        )
        
        ai_code = ai_response['response']
        
        # Extract python code robustly
        match = re.search(r'```python(.*?)```', ai_code, re.DOTALL | re.IGNORECASE)
        if match:
            code_to_run = match.group(1).strip()
        else:
            code_to_run = ai_code.strip()

        # Intercept and fix the tiny AI's stubbornness!
        # Automatically convert strict equality like df['col'] == 'text' to a fuzzy search
        code_to_run = re.sub(
            r"(df\['[^']+'\])\s*==\s*(['\"][^'\"]+['\"])", 
            r"\1.astype(str).str.contains(\2, case=False, na=False)", 
            code_to_run
        )

        # Execute the AI-generated code
        local_vars = {'df': df, 'pd': pd}
        excel_base64 = None
        try:
            exec(code_to_run, globals(), local_vars)
            
            # Extract result
            if 'result' in local_vars:
                res = local_vars['result']
                # If it's a dataframe or series, convert to string nicely
                if isinstance(res, (pd.DataFrame, pd.Series)):
                    if res.empty:
                        final_output = f"No data found matching your query (Empty DataFrame).\n\n--- Code Generated by AI ---\n{code_to_run}"
                    else:
                        final_output = f"{res.to_string()}\n\n--- Code Generated by AI ---\n{code_to_run}"
                        
                        # Convert data to an Excel file in memory
                        res_df = pd.DataFrame(res)
                        output_buffer = io.BytesIO()
                        with pd.ExcelWriter(output_buffer, engine='openpyxl') as writer:
                            res_df.to_excel(writer, index=False)
                        excel_base64 = base64.b64encode(output_buffer.getvalue()).decode('utf-8')
                        
                else:
                    final_output = f"{str(res)}\n\n--- Code Generated by AI ---\n{code_to_run}"
            else:
                final_output = f"Code executed successfully, but 'result' variable was not created.\n\nCode:\n{code_to_run}"
                
        except Exception as exec_err:
            final_output = f"Oops! The AI made a small code error.\nError: {exec_err}\n\nCode it tried to run:\n{code_to_run}"

        return {
            "status": "success",
            "prompt": prompt,
            "response": final_output,
            "excel_base64": excel_base64
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error processing data: {str(e)}")
